### ISSUE TITLE
Tests - Perform nightly test run against main

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1014]
### Descriptive summary

When we cut over to "main" from "master", we forgot to update our circle workflow to point the nightly test run against the new default branch. PR forthcoming.

From .circleci/config.yml

```yaml
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
```

### Expected behavior

Nightly test run would perform against main branch.

### Actual behavior

Nightly test run performs against master branch.
