### ISSUE TITLE
I18n: missing GeoTIFF file download translation

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1233]
### Descriptive summary

GBL v4+. Missing a translation key/value pair for export_geotiff_link.

```yaml
  ...
      export_formats: 'Export Formats'
      export_link: 'Export %{download_format}'
      export_shapefile_link: 'Shapefile'
      export_kmz_link: 'KMZ'
      export_geojson_link: 'GeoJSON'
    home:
  ...

```

<img width="1256" alt="Screen Shot 2022-07-12 at 9 53 22 AM" src="https://user-images.githubusercontent.com/69827/178520309-4b27bee1-7030-4c0b-aed4-bed5ceb89c30.png">

### Expected behavior

Expect to not see any `translation_missing` errors on the page, like:

<img width="1256" alt="Screen Shot 2022-07-12 at 9 53 50 AM" src="https://user-images.githubusercontent.com/69827/178520391-970b6a4b-6946-48c5-97d7-03dda80d4443.png">
