### ISSUE TITLE
"Member Of" metadata field does not trigger list of members on collection page

### ISSUE THREAD

**Issue by rmseifried** [geoblacklight/geoblacklight#1290]
### Descriptive summary

The Aardvark field `pcdm_memberOf_sm` is one of several new fields that triggers a relationship widget to appear on the item view page. The goal of this field is to link items that are part of a collection. Currently the vanilla app is only working in one direction: the member page shows the collection record, but the collection page does not show the list of members. 
 
### Expected behavior

If there is a record with `pcdm_memberOf_sm` linking to a collection record, the collection record should display a "Collection records..." relationship widget, as in [this example](https://geo.btaa.org/catalog/64bd8c4c-8e60-4956-b43d-bdc3f93db488):

![Screenshot 2023-04-10 at 2 36 13 PM](https://user-images.githubusercontent.com/36506059/230969715-11bfc4e4-324d-4521-971e-1e55fe870803.png)

### Actual behavior

The collection record does not display a list of members.

### Suggested solution

Code in the Big Ten's development branch seems to work correctly, so it might be okay to just copy over what they're using into the vanilla app code. It's worth noting that Big Ten has several other modifications in their relationship fields, and we might want to review these differences and consider porting over other relationships, too.

#### `config/locales/geoblacklight.en.yml` 
[Vanilla app](https://github.com/geoblacklight/geoblacklight/blob/v4.0.0/config/locales/geoblacklight.en.yml#:~:text=member_of%3A%20%27Belongs%20to%20collection...%27) 

```
relations:
  ...
  member_of: 'Belongs to collection...'
```

Suggested:
```
relations:
  ...
  member_of_ancestors: 'Belongs to collection...'
  member_of_descendants: 'Collection records...'
```

#### `geoportal/lib/generators/geoblacklight/templates/settings.yml`
[Vanilla app](https://github.com/geoblacklight/geoblacklight/blob/v4.0.0/lib/generators/geoblacklight/templates/settings.yml#:~:text=RELATIONSHIPS_SHOWN%3A-,MEMBER_OF%3A,label%3A%20geoblacklight.relations.member_of,-PART_OF_ANCESTORS%3A) 

```
RELATIONSHIPS_SHOWN:
  ...
  MEMBER_OF:
    field: pcdm_memberOf_sm
    query_type: ancestors
    icon: nil
    label: geoblacklight.relations.member_of
```

Suggested:
```
RELATIONSHIPS_SHOWN:
  ...
  MEMBER_OF_ANCESTORS:
    field: pcdm_memberOf_sm
    query_type: ancestors
    icon: parent-item
    label: geoblacklight.relations.member_of_ancestors
  MEMBER_OF_DESCENDANTS:
    field: pcdm_memberOf_sm
    query_type: descendants
    icon: child-item
    label: geoblacklight.relations.member_of_descendants
```

### Related work

* Pull request that added the relationship widgets: https://github.com/geoblacklight/geoblacklight/pull/1063
* Related issue: https://github.com/geoblacklight/geoblacklight/issues/1264
